### ISSUE TITLE
Read and set parameter examples

### ISSUE THREAD

**Issue by ajk1982** [nickovs/kld7#4]
Hi,

I have been able to get the example code in the README working using an FTDI TTL to USB Serial Converter. Radar sensor now streams TDAT data to the terminal. I really appreciate the time you spent creating this driver!

I was wondering if you could please add some example code snippets to the README on how to read and set the parameters? I am totally new to python and programming in general and I have no idea what you mean when you say: "These paramters can be read and set though a [:any:`RadarParamProxy`](https://github.com/nickovs/kld7/issues/new#id1) object accessible as the [:any:`params`](https://github.com/nickovs/kld7/issues/new#id3) attribute of the driver object."

Many thanks,
Anthony

**Comment by ajk1982** [comment]
With help from a friend I managed to get it working:
```
    with KLD7("/dev/tty.usbserial-FTBXDIFU") as radar:
    radar.params.RSPI = 3  # Maximum speed. 0=12.5km/h, 1=25km/h, 2=50km/h, 3=100km/h
    radar.params.RRAI = 2  # Maximum range. 0=5m, 1=10m, 2=30m, 3=100m
    radar.params.DEDI = 2  # Detection direction. 0 = Approaching, 1 = Receding, 2 = Both
    print(radar.params.RSPI, radar.params.RRAI, radar.params.DEDI)
```

**Comment by WULFFJ** [comment]
with KLD7("/dev/tty.usbserial-FTBXDIFU") as radar:
    radar.params.RSPI = 3  # Maximum speed. 0=12.5km/h, 1=25km/h, 2=50km/h, 3=100km/h
    radar.params.RRAI = 2  # Maximum range. 0=5m, 1=10m, 2=30m, 3=100m
    radar.params.DEDI = 2  # Detection direction. 0 = Approaching, 1 = Receding, 2 = Both
    print(radar.params.RSPI, radar.params.RRAI, radar.params.DEDI)
    
    found this is the correct way to reset params, so what is the correct way to send the RFSE command
