### ISSUE TITLE
Reset to factory settings

### ISSUE THREAD

**Issue by Haris-Muawiz-Khan** [nickovs/kld7#5]
Hi,

I ran the program to get the raw ADC data using the highest baud rate possible i.e., 3000000. It worked fine however after disconnecting the radar and re-running the program the next day it gives the following error:

`
line 253, in _read_packet
    raise Exception("Timeout waiting for reply")
Exception: Timeout waiting for reply
`

I am new to using the radar sensor and would really appreciate any help I can get as to what may be causing the error and better still how to reset the device to factory settings.

**Comment by ajk1982** [comment]
The sensor always starts up with its default baud rate, 115200
